### ISSUE TITLE
ArgumentNullException raised when calling StateInteger.SearchAllSolutions

### ISSUE THREAD

**Issue by G3Kappa** [lifebeyondfife/Decider#59] opened 2022-07-17 20:51 UTC
I'm trying to enumerate all solutions for a custom point structure `P(X, Y)` where the variables X and Y are defined as having the domain `[0, 10]`. I'm expecting `11*11 = 121` solutions in the unconstrained case. The solver returns all solutions correctly, but fails at the very end with a NRE.

![image](https://user-images.githubusercontent.com/6323641/179424224-1ff0787e-e827-4c76-af34-9b6447ef0119.png)

![image](https://user-images.githubusercontent.com/6323641/179424351-542bb60b-7855-4e8c-a7c4-55c5b281aaf9.png)

**Comment by lifebeyondfife** [comment] 2022-07-17 21:07
Hi Kevin, thanks for trying out Decider.

I should hopefully be able to work out what variable `node` is set to a `null` reference. I'd need the sourcecode so I can recreate the bug. Is there a branch you could share me to?

Cheers,
Iain

**Comment by G3Kappa** [comment] 2022-07-17 21:13
Hi Iain,

Thank you for the incredibly fast reply.

I've managed to isolate the problem to these two lines:

```csharp
var state = new StateInteger(new[] { new VariableInteger("X", 0, 10), new VariableInteger("Y", 0, 10) }, Enumerable.Empty<IConstraint>());
state.SearchAllSolutions();
```

**Comment by lifebeyondfife** [comment] 2022-07-17 21:20
I think I see, so there's no actual constraint, it's enumerating every pair from `[(0, 0), (0, 1), ... (10, 10)]`.

I should have some time to look into this tomorrow. I'll be in touch if I cannot reproduce the error.

**Comment by G3Kappa** [comment] 2022-07-17 21:35
No worries! For the time being and as far as I'm concerned catching the exception seems to be working. 

This is just a fresh hobby project so I'm not worried about leaving that in for a while, assuming nothing else breaks (I'll let you know, in case).

Anyway, thank you for creating this project.

**Comment by lifebeyondfife** [comment] 2022-07-23 09:55
This bug has been fixed by https://github.com/lifebeyondfife/Decider/pull/60. Thanks once more, @G3Kappa. Hope Decider is useful for your hobby project.

**Closed by lifebeyondfife** 2022-07-23 09:55 UTC
