### ISSUE TITLE
Boolean Solver

### ISSUE THREAD

**Issue by mafifi** [lifebeyondfife/Decider#17] opened 2019-02-24 22:49 UTC
I am trying to use Decider to solve boolean bitwise problems.  However the solver doesn't seem to find any solutions, even for relatively simple problems.  Is this an issue?

            var variables = new List<IVariable<int>>();
            var w0_31 = new VariableInteger("w0_31", 0, 1);
            variables.Add(w0_31);
            var w0_30 = new VariableInteger("w0_30", 0, 1);
            variables.Add(w0_30);

            var constraints = new List<IConstraint>();

            constraints.Add(new ConstraintInteger(!w0_30 & w0_31 == 0));
            constraints.Add(new ConstraintInteger(w0_30 & !w0_31 == 0));

            IState<int> state = new StateInteger(variables, constraints);
            state.StartSearch(out StateOperationResult searchResult, out IList<IDictionary<string, IVariable<int>>> solutions);

            // no Solutions found here
        }

**Comment by mafifi** [comment] 2019-02-24 23:25
As I stepped through it, I noted that order of precedence wasn't being obeyed.

Now I get two solutions (just incorrect ones).  However, `!` is not working as it should.

            constraints.Add(new ConstraintInteger(((!w0_30) & w0_31) == 0));
            constraints.Add(new ConstraintInteger((w0_30 & (!w0_31)) == 0));

**Comment by lifebeyondfife** [comment] 2019-02-25 23:44
For your second code snippet I'm getting two solutions: (w0_30 == 0, w0_31 == 0) and (w0_30 == 1, w0_31 == 1), which appears correct to me.

Completely agree that something's going awry with the original code snippet. When I try searching for all solutions, it goes into an infinite loop.

I believe the issue is not with the unary constraint !, but rather the binary one &. Using brackets like so ((!w0_30 & w0_31) == 0) is enough to get the solver to behave as expected.

Despite this workaround, I want to know what's going on so hope to look into this further at some point. I doubt I'll get a chance any time soon though.

Thanks for raising this issue with me - it's much appreciated.

**Comment by lifebeyondfife** [comment] 2019-07-29 22:58
I suspect this could be a cause of the issue: https://github.com/lifebeyondfife/Decider/blob/master/Csp/Integer/ExpressionInteger.cs#L892

If the solver thinks that an expression has been propagated when it hasn't i.e. the state going into the while loop is unchanged, then this causes an infinite loop.

**Comment by lifebeyondfife** [comment] 2019-08-11 15:47
Fix is in: https://github.com/lifebeyondfife/Decider/commit/6d737d073758fe3fb41c435b339d7eb5f083f5a5

Thanks for your feedback mafifi, much appreciated.

**Closed by lifebeyondfife** 2019-08-11 15:47 UTC
